#!/bin/bash

# Set the backup directory
BACKUP_DIR=/backallup/backups

# Check for dependencies
DEPENDENCIES=("tar" "jq" "ip" "hostname" "uname" "date")
for DEPENDENCY in "${DEPENDENCIES[@]}"; do
    if ! command -v "$DEPENDENCY" &>/dev/null; then
        echo "Error: $DEPENDENCY is not installed. Please install it and try again."
        exit 1
    fi
done

# Define the help message
HELP_MESSAGE="
Usage: backallup [options]

Options:
    -h, --help      Display this help message
    -p, --profile   Specify the profile name
    -d, --domain    Specify the domain name
    -j, --json      Specify the custom JSON file
    -r, --restore   Restore a backup file
    -s, --server    Backup the entire server
    --skip-backups  Skip backing up the /backallup/backups folder

Examples:
    backallup myfile.txt
    backallup -p myprofile -d mydomain
    backallup -p myprofile -j custom.json
    backallup -s
    backallup -s --skip-backups
    backallup -r myfile.tar.gz
    backallup -r -o myfile.tar.gz
"

# Get the command line arguments
options=$(getopt -o hp:d:j:r:s:o --long help,profile:,domain:,json:,restore:,server,skipbks,original -- "$@")
eval set -- "$options"

while true; do
    case "$1" in
        -h|--help)
            echo "$HELP_MESSAGE"
            exit 0
            ;;
        -p|--profile)
            PROFILE_NAME="$2"
            shift 2
            ;;
        -d|--domain)
            DOMAIN="$2"
            shift 2
            ;;
        -j|--json)
            CUSTOM_JSON_FILE="$2"
            shift 2
            ;;
        -r|--restore)
            RESTORE_FILE="$2"
            shift 2
            ;;
        -s|--server)
            SERVER_BACKUP="true"
            shift
            ;;
        --skipbks)
            SKIP_BACKUPS="true"
            shift
            ;;
        -o|--original)
            ORIGINAL_PATH="true"
            shift
            ;;
        --)
            shift
            break
            ;;
    esac
done

# Set the hostname, IP address, OS name, and datetime
HOSTNAME=$(hostname)
IPADDRESS=$(dig +short $(hostname) | head -1)
if [ "$IPADDRESS" = "" ]; then
    IPADDRESS=$(ip addr show | grep "inet " | head -1 | awk '{print $2}' | cut -d/ -f1)
fi
OSNAME=$(lsb_release -ds | xargs | tr ' ' '_')
DATETIME=$(date +%d-%m-%Y_%H-%M-%S)

# Implement the backallup commands
if [ "$SERVER_BACKUP" = "true" ]; then
    # Create the backup file
    FILENAME="${HOSTNAME}_${IPADDRESS}_${OSNAME}_${DATETIME}.tar.gz"
    BACKUP_PATH="${BACKUP_DIR}/${FILENAME}"

    # Create the backup
    if [ "$SKIP_BACKUPS" = "true" ]; then
        echo "Skipping ${BACKUP_DIR} from backup..."
        sudo tar -cvpzf ${BACKUP_PATH} --exclude=${BACKUP_DIR} --exclude=${BACKUP_PATH} --one-file-system /
        echo "Full Backup, without ${BACKUP_DIR} created in: ${BACKUP_PATH}"
    else
        sudo tar -cvpzf ${BACKUP_PATH} --exclude=${BACKUP_PATH} --one-file-system /
        echo "Full Backup created in: ${BACKUP_PATH}"
    fi

    # Output the backup file name to the terminal
    echo "You will find it here ${BACKUP_DIR}/${HOSTNAME}_${IPADDRESS}_${OSNAME}_${DATETIME}.tar.gz"

elif [ "$1" != "" ]; then
    # Get the file or directory name
    FILE_OR_DIRECTORY=$1

    # Get the basename of the file or directory
    FILE_OR_DIRECTORY=$(basename "$FILE_OR_DIRECTORY")

    # Create the backup file
    if ! tar -cvpzf "${BACKUP_DIR}/${FILE_OR_DIRECTORY}_${DATETIME}.tar.gz" "$1"; then
        echo "Error: Failed to create backup file."
        exit 1
    fi

    # Output the backup file name to the terminal
    echo "Backup file created: ${BACKUP_DIR}/${FILE_OR_DIRECTORY}_${DATETIME}.tar.gz"
elif [ "$PROFILE_NAME" != "" ]; then
    # Get the profile configuration
    PROFILE_CONFIG=$(jq -r ".${PROFILE_NAME}" /backallup/profiles/allback2struct.json)

    if [ "$DOMAIN" != "" ]; then
        # Create the backup file
        if ! tar -czf "${BACKUP_DIR}/${PROFILE_NAME}_${DOMAIN}_${DATETIME}.tar.gz" "${ PROFILE_CONFIG}"; then
            echo "Error: Failed to create backup file."
            exit 1
        fi

        # Output the backup file name to the terminal
        echo "Backup file created: ${BACKUP_DIR}/${PROFILE_NAME}_${DOMAIN}_${DATETIME}.tar.gz"
    else
        # Create the backup file
        if ! tar -czf "${BACKUP_DIR}/${PROFILE_NAME}_${DATETIME}.tar.gz" "${PROFILE_CONFIG}"; then
            echo "Error: Failed to create backup file."
            exit 1
        fi

        # Output the backup file name to the terminal
        echo "Backup file created: ${BACKUP_DIR}/${PROFILE_NAME}_${DATETIME}.tar.gz"
    fi
elif [ "$RESTORE_FILE" != "" ]; then
    # Restore the backup
    if [ ! -f "$RESTORE_FILE" ]; then
        echo "Error: Restore file not found."
        exit 1
    else
        # Check if the -o option is specified
        if [ "$ORIGINAL_PATH" = "true" ]; then
            # Extract the contents of the backup file to the original path
            if ! tar -xvpzf "$RESTORE_FILE" -C /; then
                echo "Error: Failed to restore backup file."
                exit 1
            fi
        else
            # Create a temporary directory to extract the files to
            TMP_DIR=$(mktemp -d)
            if ! tar -xvpzf "$RESTORE_FILE" -C "$TMP_DIR"; then
                echo "Error: Failed to restore backup file."
                exit 1
            else
                for dir in $(find "$TMP_DIR" -maxdepth 1 -type d); do
                    if [ "$dir" != "$TMP_DIR" ]; then
                        # Get the name of the directory
                        dir_name=$(basename "$dir")
                        # Construct the new path
                        new_path="${dir_name}__BAU"

                        # Move the directory to its new location
                        if [ -d "/$dir_name" ]; then
                            echo "moving $dir to ${new_path}"
                            mv "$dir" "${new_path}"
                        else
                            echo "moving $dir to ${new_path}"
                            mkdir -p "${new_path%/*}"
                            mv "$dir" "$new_path"
                        fi
                    fi
                done
                # Remove the temporary directory
                rm -rf "$TMP_DIR"
            fi
        fi
        echo "Backup file restored successfully."
    fi
fi
